<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [3]:
df = pd.read_csv("C:/Users/USER/Desktop/py-master/ML/4_save_model/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [9]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [15]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\USER\anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [16]:
mj = joblib.load('model_joblib')

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432

In [19]:
mj.predict([[5000]])

array([859554.79452055])